### ISSUE TITLE
pragmas, relation to dashawn888/sqlite3worker

### ISSUE THREAD

**Issue by codinguncut** [roshanlam/sqlite-worker#1]
Hi,
thank you very much for sharing this library, it has been of great use to me.

I have two questions:
- I would like to run pragmas (https://phiresky.github.io/blog/2020/sqlite-performance-tuning/) once when opening the database, but don't want to do so once for every worker. Would it be possible to add actions to be executed once at time of opening the database i.e. in `_process_queries`?
- Are you aware of https://github.com/dashawn888/sqlite3worker and https://github.com/palantir/sqlite3worker? These seem to be quite similar to your library

Thank you.

**Comment by codinguncut** [comment]
Sorry for all the back and forth.

Below my suggestion, sorry it's not a pull request.

- Implemented initial actions to be executed before any workers start
- Implemented max_count so that commits happen regularly if there is a constant stream of messages on the queue

```
class SqliteWorkerMine(SqliteWorker):
    def __init__(self, file_name, max_queue_size=100, execute_init=(), max_count=50):
        super().__init__(file_name=file_name, max_queue_size=max_queue_size)
        self.execute_init = execute_init
        self.max_count = max_count

    def _process_queries(self):
        with sqlite3.connect(self._file_name, check_same_thread=False,
                detect_types=sqlite3.PARSE_DECLTYPES) as conn:
            cursor = conn.cursor()
            for action in self.execute_init:
                cursor.execute(action)
                conn.commit()

            count = 0
            while not self._close_event.is_set() or not self._sql_queue.empty():
                try:
                    token, query, values = self._sql_queue.get(timeout=1)
                except queue.Empty:
                    continue

                if query:
                    count += 1
                    self._execute_query(cursor, token, query, values)

                if count > self.max_count or self._sql_queue.empty():
                    count = 0
                    conn.commit()
```

**Comment by roshanlam** [comment]
Hello,

Sorry for the late reply.

Thank you for your suggestion and the code example. To address your question about running pragmas only once when opening the database and avoiding execution for every worker, I have incorporated your suggestion into the SqliteWorker class.

I am aware of [Palantir's sqlite3worker](https://github.com/palantir/sqlite3worker). I was planning to use their library for a project, but it did not meet my needs. Additionally, since their library has been archived, I decided to write my own implementation.

I have published the changes, and I have also included your contribution in the Acknowledgements section of the README. Thank you for your valuable input!

Best regards,
Roshan
